// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfbkP33YSZJvZ9DaOSRv7_9HATZ-Qqpu8',
    appId: '1:578796026792:web:2a44e68b500b9fd654fb9d',
    messagingSenderId: '578796026792',
    projectId: 'baithak-library',
    authDomain: 'baithak-library.firebaseapp.com',
    storageBucket: 'baithak-library.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWQFfs1bth5S6bkEb8SHnhLjozElVZXY',
    appId: '1:578796026792:android:30cab49e9c52968e54fb9d',
    messagingSenderId: '578796026792',
    projectId: 'baithak-library',
    storageBucket: 'baithak-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmvNQ0G0fAep67vMAhIHCKNfvzOynQjp8',
    appId: '1:578796026792:ios:7d7083b51458cb1854fb9d',
    messagingSenderId: '578796026792',
    projectId: 'baithak-library',
    storageBucket: 'baithak-library.firebasestorage.app',
    iosBundleId: 'com.example.baithakLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmvNQ0G0fAep67vMAhIHCKNfvzOynQjp8',
    appId: '1:578796026792:ios:7d7083b51458cb1854fb9d',
    messagingSenderId: '578796026792',
    projectId: 'baithak-library',
    storageBucket: 'baithak-library.firebasestorage.app',
    iosBundleId: 'com.example.baithakLibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfbkP33YSZJvZ9DaOSRv7_9HATZ-Qqpu8',
    appId: '1:578796026792:web:11c26a45ae5c751054fb9d',
    messagingSenderId: '578796026792',
    projectId: 'baithak-library',
    authDomain: 'baithak-library.firebaseapp.com',
    storageBucket: 'baithak-library.firebasestorage.app',
  );
}
